import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Developer Workflow Collection | Prompt Machine",
  description: "Current release status for Prompt Machine's first paid workflow collection.",
};

export default function DeveloperPackPage(){return <main><section className="pageHero"><div className="wrap"><span className="stateHold">NOT FOR SALE · RELEASE HARDENING</span><div className="eyebrow">COLLECTION 01 / BUILD & SHIP</div><h1>Developer Workflow Collection</h1><p className="lead">The first paid Prompt Machine collection is being built around recurring software work: code review, bug diagnosis, technical decisions, and AI workflow design. The product is the reusable workflow system—not a ZIP customers have to reverse-engineer.</p><div className="actions"><Link className="btn btnPrimary" href="/free/developer-starter-pack">Use 3 free workflows first</Link><Link className="btn btnSecondary" href="/collections">Browse collections</Link></div><p className="notice"><strong>Planned launch price: $19 one-time.</strong> This remains a pricing hypothesis. Checkout stays disabled until behavioral, parity, archive, delivery, and provider-canary evidence closes the release gates.</p></div></section><section className="section"><div className="wrap"><div className="grid2"><article className="card"><h3>What the paid collection must earn</h3><ul className="list"><li>Four related workflow families instead of isolated prompt files</li><li>Installable skill surfaces where supported</li><li>Reusable operating contracts and adaptation guidance</li><li>Examples that show how to apply the workflows</li><li>Visible evidence, known limitations, and version boundaries</li><li>A delivery experience that makes the starting point obvious</li></ul></article><article className="card"><h3>Current evidence boundary</h3><p><strong>CANDIDATE / NOT FOR SALE</strong></p><p>Skill structure and test infrastructure have advanced, but real behavioral execution, improvement, certification, portability, and paid-market validation remain separate gates.</p><p><code>marketing claim &lt;= observed evidence</code></p></article></div></div></section><section className="section"><div className="wrap"><div className="sectionHeader splitHeader"><div><div className="eyebrow">WHY THIS EXISTS</div><h2>The upgrade must remove more work than the free layer.</h2></div><p className="sectionIntro">The free workflows remain useful standalone products. The collection is only worth paying for if broader coverage, reusable policies, skills, examples, and adaptation save enough setup and trial-and-error to justify the purchase.</p></div></div></section></main>}
