import type { Metadata } from "next";
import Link from "next/link";
import { CODE_REVIEW } from "@/lib/public-products";
import { FREE_ASSETS } from "@/lib/verlune-free-catalog";

export const metadata: Metadata = {
  title: "License",
  description: "Usage rights and boundaries for Verlune Code Review and the Verlune Free Library. The license included with each product governs its use.",
  alternates: { canonical: "/license" },
};

export default function LicensePage() {
  return <main><section className="pageHero"><div className="wrap"><div className="eyebrow">VERLUNE / LICENSE</div><h1>Your work.<br />Clear boundaries.</h1><p className="lead">Use the workflows in your own work. Adapt them for your needs. Keep the product materials within the permissions of their included license.</p><p className="notice">This page is a summary. The packaged <code>CUSTOMER-LICENSE.md</code> governs {CODE_REVIEW.name}; the included <code>LICENSE.md</code> governs the Verlune Free Library. Checkout and product-specific sale terms also apply to a purchase.</p></div></section>
    <section className="section"><div className="wrap"><div className="eyebrow">{CODE_REVIEW.name.toUpperCase()}</div><h2>A license for the version you purchase.</h2><p className="sectionIntro">After a valid authorized purchase, the purchaser receives a perpetual, non-exclusive, non-transferable license to the purchased version, subject to the packaged license terms.</p><div className="grid2"><article className="card"><h3>You may</h3><ul className="list"><li>Use the workflow for personal, commercial, and client software projects.</li><li>Copy it into private tools, repositories, assistants, or internal systems you control.</li><li>Adapt it for your own internal use.</li><li>Use, share, and commercialize review outputs, subject to model-provider terms and rights in your inputs.</li><li>As an organizational purchaser, allow employees and contractors to use it internally while acting on your behalf.</li></ul></article><article className="card"><h3>You may not</h3><ul className="list"><li>Resell, sublicense, rent, or redistribute the workflow as a standalone product.</li><li>Publish the workflow or a substantially equivalent derivative for public download.</li><li>Share the source workflow with unrelated third parties for their independent use.</li><li>Package it as a competing prompt pack, workflow library, template collection, or marketplace item.</li><li>Misrepresent its identity or imply a broader evidence or certification scope.</li></ul></article></div></div></section>
    <section className="section"><div className="wrap splitHeader"><div><div className="eyebrow">VERLUNE FREE LIBRARY</div><h2>Free to use.<br />Licensed to adapt.</h2></div><div><p>The current Free Library contains {FREE_ASSETS.length} launch-core assets: eight structured prompts and three structured workflows. Its included <code>LICENSE.md</code> governs those Free Library materials.</p><p>The Free Library permits use and adaptation for personal, educational, professional, internal business, application, product, and service use. You may use outputs subject to applicable third-party terms.</p><p>You may incorporate adapted logic into your own product or service when the Free Library itself is not exposed, extractable, downloadable, or redistributed as a substitute. Resale, publication, sharing, and redistribution of the materials or substantial portions are restricted by the included license.</p></div></div></section>
    <section className="section"><div className="wrap grid2"><article className="card"><h2>You keep responsibility for the result.</h2><p>The paid workflow is advisory. Its declared evidence covers {CODE_REVIEW.evidenceSummary.model}; other models are not covered. It does not automatically approve code or guarantee correctness, security, compliance, or defect detection.</p><p>The license does not claim ownership of your code, confidential information, project data, or review outputs. Your chosen AI provider’s terms and privacy practices apply separately.</p></article><article className="card"><h2>What a purchase includes.</h2><p>The delivered version, not a promise of future versions, consulting, custom implementation, or ongoing support. Model access and usage fees are separate.</p><p>Payment and refunds are handled under the merchant of record’s terms and applicable mandatory consumer rights. A fully refunded, reversed, or charged-back purchase ends its license as described in the packaged terms. Non-waivable rights remain unaffected.</p></article></div><div className="wrap actions"><Link className="btn btnPrimary" href="/code-review">Explore Code Review</Link><Link className="btn btnSecondary" href="/free">Try free workflows</Link></div></section>
  </main>;
}
